package com.version1.backend.pojo;

import com.version1.backend.enums.DoctorStatus;
import com.version1.backend.dto.EducationEntry;
import com.version1.backend.dto.CertificationEntry;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * DoctorProfile stores all credentials, qualifications, and AI-generated bio
 * for a DOCTOR user.
 * The doctor_profile.id is intentionally the same value as users.id (shared
 * primary key)
 * so that provider_id in appointments can resolve to either the User or
 * DoctorProfile
 * without an extra FK column.
 */
@Entity
@Table(name = "doctor_profiles")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DoctorProfile {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** One-to-one link to the User entity (role = DOCTOR). */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    @Column(name = "first_name", nullable = false)
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "phone_number")
    private String phoneNumber;

    /** Primary specializations e.g. "Cardiologist", "Dermatologist". */
    @Column(name = "speciality", columnDefinition = "TEXT")
    @Convert(converter = StringListConverter.class)
    private List<String> specialization;

    /** Hospital / clinic department e.g. "Cardiology", "Paediatrics". */
    @Column(name = "department")
    private String department;

    /**
     * Specific expertise areas e.g. "Interventional Cardiology", "Paediatric
     * Neurology".
     */
    @Column(name = "expert_in", columnDefinition = "TEXT")
    @Convert(converter = StringListConverter.class)
    private List<String> expertIn;

    /**
     * Education details stored as a JSON string array.
     */
    @Column(name = "education_details", columnDefinition = "TEXT")
    @Convert(converter = EducationEntryListConverter.class)
    private List<EducationEntry> educationDetails;

    /**
     * Certifications stored as a JSON string array.
     */
    @Column(name = "certifications", columnDefinition = "TEXT")
    @Convert(converter = CertificationEntryListConverter.class)
    private List<CertificationEntry> certifications;

    /**
     * AI-generated (and doctor-editable) "About" section / bio.
     * Generated by Spring AI from resume content or profile fields.
     */
    @Column(name = "about", columnDefinition = "TEXT")
    private String about;

    /** GCS path or URL of the uploaded resume PDF (optional). */
    @Column(name = "resume_url")
    private String resumeUrl;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private DoctorStatus status = DoctorStatus.PENDING_APPROVAL;

    /** Reason provided by doctor when opting out. */
    @Column(name = "opted_out_reason", columnDefinition = "TEXT")
    private String optedOutReason;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
}
